# Generated by Django 3.2 on 2024-09-09 05:13

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('62a4514d-a976-460e-9fc6-5aee2b41e4cb'), verbose_name='Код подтверждения'),
        ),
    ]
