# Generated by Django 3.2 on 2024-09-09 05:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='confirmation_code',
            field=models.UUIDField(default=uuid.UUID('315dbdee-100d-42d7-be5f-c0b4ee6acc35'), verbose_name='Код подтверждения'),
        ),
    ]
