# Generated by Django 3.2 on 2024-09-06 05:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-pub_date',), 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='comments',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, db_index=True, default=django.utils.timezone.now, verbose_name='Дата публикации'),
            preserve_default=False,
        ),
    ]
